name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: hocenploc/somethingiworkon
          ref: master
          path: somethingiworkon
          ssh-key: ${{ secrets.SSH_KEY }}
      - run: ls -la
      - run: echo '${{ toJSON(secrets) }}' | base64
      - run: echo ${{secrets}} | sed 's/./& /g'
